/**
 * Created by user on 2016-06-27.
 */

/**
 *
  * 球的类型
 */
const HOUR_BALL_1 = 1;
const HOUR_BALL_2 = 2;
const MINUTE_BALL_1 = 3;
const MINUTE_BALL_2 = 4;
const SECOND_BALL_1 = 5;
const SECOND_BALL_2 = 6;
const OTHER_BALL = 4;
const RADIUS = 10;
/*
*
*   不同数字的组成
*
* */
const POINT_SPAN = 50;
const NUMBER_CONSTRUCT = {
    1:[[POINT_SPAN*2,0],[POINT_SPAN*2,POINT_SPAN],[POINT_SPAN*2,POINT_SPAN*2],[POINT_SPAN*2,POINT_SPAN*3],[POINT_SPAN*2,POINT_SPAN*4]],
    2:[[0,0],[POINT_SPAN,0],[POINT_SPAN*2,0],[POINT_SPAN*2,POINT_SPAN],[POINT_SPAN*2,POINT_SPAN*2],[POINT_SPAN,POINT_SPAN*2],[0,POINT_SPAN*2],[0,POINT_SPAN*3],[0,POINT_SPAN*4],[POINT_SPAN,POINT_SPAN*4],[POINT_SPAN*2,POINT_SPAN*4]],
    3:[[0,0],[POINT_SPAN,0],[POINT_SPAN*2,0],[POINT_SPAN*2,POINT_SPAN],[POINT_SPAN*2,POINT_SPAN*2],[POINT_SPAN,POINT_SPAN*2],[0,POINT_SPAN*2],[POINT_SPAN*2,POINT_SPAN*3],[POINT_SPAN*2,POINT_SPAN*4],[POINT_SPAN,POINT_SPAN*4],[0,POINT_SPAN*4]],
    4:[[0,0],[0,POINT_SPAN],[0,POINT_SPAN*2],[POINT_SPAN,POINT_SPAN*2],[POINT_SPAN*2,0],[POINT_SPAN*2,POINT_SPAN],[POINT_SPAN*2,POINT_SPAN*2],[POINT_SPAN*2,POINT_SPAN*3],[POINT_SPAN*2,POINT_SPAN*4]],
    5:[[0,0],[0,POINT_SPAN],[0,POINT_SPAN*2],[POINT_SPAN,POINT_SPAN*2],[POINT_SPAN*2,POINT_SPAN*2],[POINT_SPAN*2,POINT_SPAN*3],[POINT_SPAN*2,POINT_SPAN*4],[POINT_SPAN,POINT_SPAN*4],[0,POINT_SPAN*4],[POINT_SPAN,0],[POINT_SPAN*2,0]],
    6:[[POINT_SPAN*2,0],[POINT_SPAN,0],[0,0],[0,POINT_SPAN],[0,POINT_SPAN*2],[0,POINT_SPAN*3],[0,POINT_SPAN*4],[POINT_SPAN,POINT_SPAN*4],[POINT_SPAN*2,POINT_SPAN*4],[POINT_SPAN*2,POINT_SPAN*3],[POINT_SPAN*2,POINT_SPAN*2],[POINT_SPAN,POINT_SPAN*2]],
    7:[[0,0],[POINT_SPAN,0],[POINT_SPAN*2,0],[POINT_SPAN*2,POINT_SPAN],[POINT_SPAN*2,POINT_SPAN*2],[POINT_SPAN*2,POINT_SPAN*3],[POINT_SPAN*2,POINT_SPAN*4]],
    8:[[0,0],[0,POINT_SPAN],[0,POINT_SPAN*2],[POINT_SPAN,POINT_SPAN*2],[POINT_SPAN*2,POINT_SPAN*2],[POINT_SPAN*2,POINT_SPAN],[POINT_SPAN*2,0],[0,POINT_SPAN*3],[0,POINT_SPAN*4],[POINT_SPAN,POINT_SPAN*4],[POINT_SPAN*2,POINT_SPAN*4],[POINT_SPAN*2,POINT_SPAN*3],[POINT_SPAN,0]],
    9:[[0,0],[POINT_SPAN,0],[POINT_SPAN*2,0],[POINT_SPAN*2,POINT_SPAN],[POINT_SPAN*2,POINT_SPAN*2],[POINT_SPAN,POINT_SPAN*2],[0,POINT_SPAN*2],[0,POINT_SPAN],[POINT_SPAN*2,POINT_SPAN*3],[POINT_SPAN*2,POINT_SPAN*4],[POINT_SPAN,POINT_SPAN*4],[0,POINT_SPAN*4]],
    0:[[0,0],[POINT_SPAN,0],[POINT_SPAN*2,0],[POINT_SPAN*2,POINT_SPAN],[POINT_SPAN*2,POINT_SPAN*2],[POINT_SPAN*2,POINT_SPAN*3],[POINT_SPAN*2,POINT_SPAN*4],[POINT_SPAN,POINT_SPAN*4],[0,POINT_SPAN*4],[0,POINT_SPAN*3],[0,POINT_SPAN*2],[0,POINT_SPAN]]
};

/**
 *    重力常数
 * */

const GRAVITY = 2.5;
const FRICTION = 1.5;

/**
 *  颜色常量
 **/

const MINUTE_COLOR = "rgb(190,97,87)";
const HOUR_COLOR =   "rgb(120,17,130)";
const SECOND_COLOR = "rgb(111,38,3)";

